import { CheckCircle2, KeyRound, LockKeyhole, ShieldCheck } from "lucide-react";
import { Link } from "react-router-dom";
import { AffiliateDisclosure } from "../components/affiliate/AffiliateDisclosure";
import { Newsletter } from "../components/Newsletter";
import { SEO } from "../components/SEO";
import { Container } from "../components/ui/Container";
import { Section } from "../components/ui/Section";
import { site } from "../utils/site";

const path = "/guides/how-password-managers-work";
const title = "How Password Managers Actually Work";
const description = "Learn how password managers generate, encrypt, sync, decrypt, autofill, share, recover, and export passwords—and what the provider can still know.";
const faq = [
  ["How does a password manager work?", "It stores credentials in an encrypted vault, derives encryption keys from account secrets, synchronizes encrypted data when cloud sync is used, decrypts locally on authorized devices, and fills matching sites or apps."],
  ["Does the provider store my master password?", "Reputable documented systems generally do not store or transmit the master password in a recoverable form, but authentication and key derivation designs differ. Check the provider's current architecture."],
  ["What is key derivation?", "A key-derivation function performs deliberately expensive computation to turn a human password into cryptographic key material and make repeated password guessing more costly."],
  ["Are passwords encrypted before upload?", "In documented end-to-end encrypted managers, vault data is encrypted on the client before cloud storage. Verify the exact product and fields rather than assuming every app follows this model."],
  ["Can the provider decrypt my vault?", "A genuine zero-knowledge architecture is designed so the provider lacks the necessary vault keys. Recovery, enterprise administration, and shared-vault designs can change the details."],
  ["What is the difference between authentication and encryption?", "Authentication proves that an account may sign in. Encryption determines whether stored vault content can be read. A system can authenticate an account without possessing the key that decrypts its vault."],
  ["How does cloud sync stay private?", "The server can store and deliver encrypted vault data. Authorized devices download the ciphertext and decrypt it locally after the user unlocks the vault."],
  ["What happens when I unlock with biometrics?", "Biometric approval normally releases or authorizes use of locally protected key material. The fingerprint or face scan is not itself the vault encryption key."],
  ["How does autofill know where a password belongs?", "The app or extension compares the current domain or app identifier with saved item metadata and offers matching credentials according to its fill rules."],
  ["Can autofill protect against phishing?", "Domain matching can help because a credential saved for one domain should not be offered to a lookalike domain. It is not perfect protection, and users should still inspect the site."],
  ["How are passwords shared securely?", "Well-designed sharing encrypts an item or vault key for another authorized account rather than sending the password as plaintext. Permissions and revocation vary by provider."],
  ["What happens during recovery?", "Recovery may restore account access, approve a device, use a trusted contact, or transfer organizational control. The model determines who can recover whom and whether vault keys can be restored."],
  ["Does MFA encrypt my vault?", "MFA usually protects online authentication. It does not automatically add strength to an encrypted vault that an attacker already stole unless the architecture explicitly uses it in key protection."],
  ["Where are passkeys stored?", "A password manager can store passkey private keys inside its encrypted vault and sync them to authorized devices. Platform passkey behavior and portability still vary."],
  ["What happens offline?", "Previously synchronized vault data can often be decrypted locally after unlock. New changes wait to synchronize until the service is reachable."],
  ["Are exports encrypted?", "Some managers offer encrypted exports, while common CSV exports are plaintext. Always check the format and remove plaintext files after migration."],
  ["Is local-only storage safer?", "It avoids some provider-side exposure but increases backup, device-loss, update, and recovery responsibilities. It is a different tradeoff, not an automatic safety upgrade."],
  ["Is self-hosting safer?", "Self-hosting changes who operates the synchronization server. The operator must maintain updates, backups, TLS, access controls, monitoring, and disaster recovery."],
  ["What happens if the company is breached?", "Attackers may obtain account or encrypted vault data depending on the incident. Strong client-side encryption limits readable content, but vault theft, metadata exposure, and targeted attacks still matter."],
  ["Why does the master password need to be unique?", "It protects the concentrated vault. Reusing it on another site could let a third-party breach undermine the password manager's security model."],
  ["Can malware read an unlocked vault?", "Malware with sufficient access to an unlocked device may capture filled credentials, clipboard contents, keystrokes, or decrypted data. Vault encryption is not a substitute for device security."],
  ["What data can the provider still know?", "Depending on the service: account email, billing, support requests, login security events, diagnostics, website analytics, and some feature-specific data such as alias routing."],
  ["Do password managers work without browser extensions?", "Yes, but extensions make saving and filling websites easier. Desktop and mobile apps can still store, generate, copy, and sometimes fill credentials through operating-system integrations."],
  ["What should I check before choosing one?", "Check encryption and metadata documentation, key derivation, MFA, recovery, audits, sharing, export formats, platform support, telemetry, account deletion, and incident response."]
];

function TextLink({ href, children }: { href: string; children: React.ReactNode }) { return <Link className="font-semibold text-teal-700 underline decoration-teal-300 underline-offset-4" to={href}>{children}</Link>; }

export function HowPasswordManagersWorkPage() {
  const canonical = `${site.url}${path}`;
  const schema = [
    { "@context":"https://schema.org", "@type":"Article", headline:title, description, mainEntityOfPage:canonical, author:{"@type":"Organization",name:site.name}, publisher:{"@type":"Organization",name:site.name}, datePublished:"2026-07-12", dateModified:"2026-07-12" },
    { "@context":"https://schema.org", "@type":"BreadcrumbList", itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:site.url},{"@type":"ListItem",position:2,name:"Password Managers",item:`${site.url}/password-managers`},{"@type":"ListItem",position:3,name:title,item:canonical}] },
    { "@context":"https://schema.org", "@type":"FAQPage", mainEntity:faq.map(([q,a])=>({"@type":"Question",name:q,acceptedAnswer:{"@type":"Answer",text:a}})) }
  ];
  const steps = [
    [KeyRound,"1. You create the vault key material","The app combines account secrets with a key-derivation process. Designs differ: Bitwarden documents PBKDF2 or Argon2id, while 1Password combines an account password with a device-generated Secret Key."],
    [LockKeyhole,"2. The client encrypts vault items","Credentials, notes, passkeys, and other supported fields are encrypted on the device in end-to-end encrypted systems. Exact metadata treatment varies."],
    [ShieldCheck,"3. Encrypted data synchronizes","The service stores ciphertext and sends it to authorized devices. Cloud sync does not require the server to hold plaintext vault contents."],
    [CheckCircle2,"4. An authorized device decrypts locally","After authentication and unlock, the client reconstructs or releases the required keys and decrypts the vault on the device."],
    [LockKeyhole,"5. Changes synchronize again","New items, edits, deletions, and password changes are encrypted before the updated vault state is synchronized."],
    [KeyRound,"6. Sharing grants controlled access","Sharing generally protects a vault or item key for another authorized account. Permissions, copies, revocation, and recovery behavior differ by product."]
  ];
  return <>
    <SEO title={title} description={description} path={path}/>
    {schema.map((item, index) => <script key={index} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(item) }} />)}
    <Section className="bg-slate-950 text-white"><Container className="py-16 lg:py-24"><div className="max-w-4xl"><p className="text-sm font-bold uppercase tracking-[0.22em] text-teal-300">Password manager explainer</p><h1 className="mt-4 text-4xl font-black tracking-tight sm:text-5xl lg:text-6xl">{title}</h1><p className="mt-6 text-xl leading-9 text-slate-200">A password manager is not simply a locked spreadsheet in the cloud. The useful systems separate authentication from encryption, derive keys on your device, synchronize ciphertext, and decrypt only for authorized clients.</p><p className="mt-5 text-sm text-slate-300">Architecture facts checked July 12, 2026. Provider implementations differ.</p></div></Container></Section>
    <Section><Container className="py-14"><AffiliateDisclosure/><div className="mt-8 rounded-3xl border border-teal-200 bg-teal-50 p-8"><h2 className="text-3xl font-black text-slate-950">Quick answer</h2><p className="mt-4 text-lg leading-8 text-slate-700">A password manager turns one strong account secret into key material, encrypts each vault before synchronization, and unlocks it locally on approved devices. The provider can deliver encrypted data without necessarily being able to read it. Recovery, sharing, metadata, telemetry, and compromised devices are the important caveats.</p></div></Container></Section>
    <Section className="bg-slate-50"><Container className="py-14"><h2 className="text-3xl font-black text-slate-950">The password lifecycle</h2><div className="mt-7 grid gap-5 md:grid-cols-2">{steps.map(([Icon,h,b])=>{const I=Icon as typeof KeyRound;return <div className="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm" key={h as string}><I className="h-7 w-7 text-teal-700"/><h3 className="mt-3 text-xl font-black">{h as string}</h3><p className="mt-2 leading-7 text-slate-700">{b as string}</p></div>})}</div></Container></Section>
    <Section><Container className="py-14"><h2 className="text-3xl font-black text-slate-950">Authentication and encryption are different</h2><div className="mt-6 max-w-full overflow-x-auto rounded-2xl border border-slate-200"><table className="min-w-[760px] w-full text-left"><thead className="bg-slate-900 text-white"><tr><th className="p-4">Layer</th><th className="p-4">Job</th><th className="p-4">What the server may hold</th><th className="p-4">Failure example</th></tr></thead><tbody className="divide-y divide-slate-200 bg-white">{[
      ["Authentication","Proves the account may sign in","Verifier, account state, MFA configuration, security events","Stolen session or credential stuffing"],
      ["Key derivation","Turns account secrets into costly-to-guess key material","Parameters and salt; not the master secret in documented designs","Weak master password enables offline guessing"],
      ["Encryption","Makes vault content unreadable without keys","Encrypted vault data","Stolen ciphertext becomes an offline target"],
      ["Synchronization","Delivers encrypted changes to devices","Ciphertext, versions, operational metadata","Rollback, availability, or account compromise"],
      ["Local unlock","Releases keys on an approved device","Normally no plaintext server copy","Malware reads an unlocked session"]
    ].map(r=><tr key={r[0]}>{r.map(c=><td className="p-4 align-top text-slate-700" key={c}>{c}</td>)}</tr>)}</tbody></table></div></Container></Section>
    <Section className="bg-slate-50"><Container className="py-14 space-y-12">{[
      ["Why key derivation matters","Human-memorable passwords have limited entropy. A key-derivation function adds salt and computational work so each password guess costs more. Bitwarden documents PBKDF2 and optional Argon2id. Work factors can change over time and should be rechecked before making provider-specific comparisons."],
      ["What zero knowledge changes","In a documented zero-knowledge design, the provider does not possess the vault keys needed to decrypt content. That limits the damage of server access, but it does not erase account records, diagnostics, support data, or every feature-specific data flow."],
      ["How cloud synchronization works","An authorized device can encrypt a new item, upload ciphertext, and let another authorized device download and decrypt it. The service still controls availability, account authentication, software delivery, and synchronization logic."],
      ["How autofill works","Browser extensions and operating-system integrations compare the current website domain or app identifier with saved items. Exact-domain matching can help resist lookalike phishing sites, but autofill behavior, frames, redirects, and compromised pages still require careful implementation."],
      ["How sharing works","A secure sharing system gives another account access to encrypted item or vault keys. Shared data may be copied, exported, or retained on an authorized device, so revoking future access cannot always erase every prior copy."],
      ["How recovery works","Recovery can mean restoring account authentication, approving a device, using a trusted contact, or letting an organizer rewrap encryption keys. Convenience increases resilience, but every recovery path changes who can help restore access."],
      ["Where MFA fits","MFA makes unauthorized online sign-in harder. It does not automatically strengthen a vault already stolen as ciphertext because offline decryption depends on the encryption design and account secrets, not a later server challenge."],
      ["How passkeys fit","A manager can store a passkey private key as another encrypted vault item and present it to the correct relying party. Portability, sharing, recovery, and platform interoperability are still evolving."],
      ["Why exports are dangerous","Migration often uses a plaintext CSV because it is broadly compatible. During that window, every exported credential may sit unencrypted on disk, in backups, or in cloud-synced folders. Prefer encrypted exports when compatible and remove plaintext files promptly."],
      ["Local-only and self-hosted designs","Local-only vaults reduce provider synchronization exposure but shift responsibility to backups and devices. Self-hosting changes the server operator while adding update, TLS, backup, monitoring, and recovery work. Neither is automatically safer."]
    ].map(([h,b])=><div key={h}><h2 className="text-3xl font-black text-slate-950">{h}</h2><p className="mt-4 max-w-4xl text-lg leading-8 text-slate-700">{b}</p></div>)}</Container></Section>
    <Section><Container className="py-14"><h2 className="text-3xl font-black text-slate-950">What the provider can still know</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{["Account email or identifier","Billing and payment-processor records","Support conversations","Login security events and abuse controls","Optional diagnostics or telemetry","Website cookies and analytics","Feature-specific data such as alias routing","Encrypted vault size, timing, and synchronization metadata"].map(x=><div className="rounded-2xl border border-slate-200 p-5 text-slate-700" key={x}>{x}</div>)}</div><p className="mt-6 leading-8 text-slate-700">For the privacy comparison, see <TextLink href="/best-password-managers-for-privacy">Best Password Managers for Privacy</TextLink>. For the broader risk question, see <TextLink href="/are-password-managers-safe">Are Password Managers Safe?</TextLink>.</p></Container></Section>
    <Section className="bg-slate-950 text-white"><Container className="py-14"><h2 className="text-3xl font-black">A practical safe-use checklist</h2><div className="mt-6 grid gap-4 md:grid-cols-2">{["Use a unique, strong master password","Enable MFA and protect recovery codes","Secure the email account tied to recovery","Install only official apps and extensions","Keep devices and browsers updated","Review new-device and session lists","Understand recovery before relying on it","Prefer encrypted exports when possible","Delete plaintext migration files","Test sharing and offboarding workflows","Remove lost or retired devices","Keep device malware defenses active"].map(x=><div className="rounded-2xl bg-white/10 p-4" key={x}>{x}</div>)}</div></Container></Section>
    <Section><Container className="py-14"><h2 className="text-3xl font-black text-slate-950">Frequently asked questions</h2><div className="mt-6 space-y-4">{faq.map(([q,a])=><details className="rounded-2xl border border-slate-200 bg-white p-5" key={q}><summary className="cursor-pointer font-bold text-slate-950">{q}</summary><p className="mt-3 leading-7 text-slate-700">{a}</p></details>)}</div></Container></Section>
    <Section className="bg-slate-50"><Container className="py-14"><h2 className="text-3xl font-black text-slate-950">Evidence checked</h2><ul className="mt-5 grid gap-3 text-sm md:grid-cols-2">{[
      ["NIST password guidance","https://www.nist.gov/cybersecurity-and-privacy/how-do-i-create-good-password"],["Bitwarden security white paper","https://bitwarden.com/help/bitwarden-security-white-paper/"],["Bitwarden key derivation","https://bitwarden.com/help/kdf-algorithms/"],["1Password authentication and encryption","https://support.1password.com/authentication-encryption/"],["1Password Secret Key","https://support.1password.com/secret-key-security/"],["1Password Secure Remote Password","https://support.1password.com/secure-remote-password/"],["Proton Pass security","https://proton.me/pass/security"],["NordPass security","https://nordpass.com/security/"]
    ].map(([l,h])=><li key={h}><a className="font-semibold text-teal-700 underline" href={h} target="_blank" rel="noreferrer noopener">{l}</a></li>)}</ul><div className="mt-10 rounded-3xl bg-white p-8 shadow-sm"><h2 className="text-3xl font-black">Final takeaway</h2><p className="mt-4 text-lg leading-8 text-slate-700">The core idea is simple: encrypt locally, synchronize ciphertext, and decrypt only for authorized clients. The meaningful differences live in key derivation, metadata, recovery, sharing, telemetry, software delivery, and device security. Use the <TextLink href="/password-managers">Password Manager Decision Hub</TextLink> when you are ready to choose a product.</p></div></Container></Section>
    <Newsletter />
  </>;
}
