import { Link } from "react-router-dom";
import { SEO } from "../components/SEO";
import { PageHeader } from "../components/ui/PageHeader";
import { Section } from "../components/ui/Section";
import { site } from "../utils/site";

type Step = { title: string; why: string; examine: string; test: string; failure: string; evidence: string; pause: string };
const steps: Step[] = [
  { title: "1. Problem fit", why: "Software is easiest to judge when the problem is concrete. A vague problem invites feature collecting and makes almost any product sound useful.", examine: "Name the situation, who is affected, and what is not working now. Separate a recurring problem from a one-time inconvenience.", test: "Write: ‘I need software to ___ because ___.’ Then ask whether an existing tool, setting, or habit already solves it.", failure: "Buying a bundle for a problem you rarely encounter, or confusing a product category with the outcome you actually want.", evidence: "Your own examples, workflow notes, and the current tool’s documented capabilities are more useful here than popularity or rankings.", pause: "Pause if you cannot describe the problem without naming a brand or feature. Continue only when the problem is important enough to justify another subscription." },
  { title: "2. Required outcomes", why: "Outcomes tell you whether software helped. Features are only means, and a long feature list can hide the absence of the one result you need.", examine: "Define two or three observable results, such as restoring a file, signing in across devices, reducing a specific exposure, or connecting reliably on a known network.", test: "Finish the sentence: ‘After 30 days, I will know this worked if ___.’ Make the result specific enough to check.", failure: "Treating ‘more protection,’ ‘better privacy,’ or ‘more productivity’ as complete outcomes without defining what changes.", evidence: "A documented workflow, support article, independent test where available, or a small personal baseline can support the outcome.", pause: "Reject a product when its documented scope does not produce the required outcome, even if its optional features look attractive." },
  { title: "3. Friction and usability", why: "A tool that technically has the right feature can still fail if the important workflow is confusing, repetitive, or easy to abandon.", examine: "Look for setup steps, warnings, permissions, defaults, recovery prompts, and the number of places you must return to maintain the service.", test: "Try the core task without a tutorial after reading the official help page. Note where you hesitate, repeat work, or need a workaround.", failure: "Calling a product ‘easy’ because the interface looks clean, while ignoring recurring setup, confusing alerts, or difficult recovery.", evidence: "Usability requirements, clear documentation, accessible support, and your own task notes are useful; marketing adjectives are not proof.", pause: "Pause when the friction affects the task you bought the software for. A discount rarely compensates for repeated daily annoyance." },
  { title: "4. True cost", why: "The advertised monthly number may omit commitment, renewal, add-ons, time, and the cost of leaving. Cost is a decision variable, not a final checkout detail.", examine: "Record first-term price, renewal price, billing interval, taxes or regional variation, annual commitment, required add-ons, extra seats or devices, setup time, maintenance, and switching effort.", test: "Before entering payment details, locate the pricing, renewal, refund, and cancellation terms. Write the highest likely ordinary cost you can verify—not a promotional headline.", failure: "Comparing an introductory annual price with a competitor’s monthly renewal price, or ignoring migration and maintenance time because it is not charged to a card.", evidence: "Current official pricing and terms are appropriate for volatile details. Mark anything regional, promotional, unclear, or unchecked.", pause: "Pause when renewal cost or commitment is unclear, or when the likely benefit does not justify both money and ongoing effort." },
  { title: "5. Limits and tradeoffs", why: "Every plan and service has boundaries. Finding them early prevents the one required workflow from failing after commitment.", examine: "Check device, seat, storage, platform, recovery, support, offline, export, feature, and account limits. Distinguish a plan limit from a provider-wide capability.", test: "Read the plan comparison and help documentation for your exact workflow. Ask what happens when you exceed the limit or lose access to a device.", failure: "Assuming ‘unlimited’ means unlimited in every relevant way, or treating more features as automatically better.", evidence: "Current provider documentation and terms support limits; independent testing is needed for performance or behavior claims.", pause: "Reject a plan when its hard limit conflicts with a must-have requirement. Continue when the tradeoff is understood and acceptable." },
  { title: "6. Privacy and security", why: "Software may handle credentials, files, browsing data, identity information, or sensitive activity. Privacy and security questions deserve context, not absolute promises.", examine: "Ask what data is collected, why it is needed, what defaults apply, who can access it, how long it is retained, and what evidence supports security claims.", test: "Read the privacy policy and security documentation for the data and threat model that matter to you. Look for omissions and assumptions, not just reassuring labels.", failure: "Treating a privacy policy, encryption mention, audit, or open-source claim as proof that a service is completely private or secure.", evidence: "Official architecture and policy documents, independent audits or testing, incident disclosures, and reputable technical analysis each answer different questions.", pause: "Pause when the provider cannot explain data handling or when the evidence does not match the sensitivity of your use. No software removes every risk." },
  { title: "7. Provider reliability", why: "The provider is part of the product. Documentation, support, ownership, incident communication, and service continuity affect whether the tool remains useful.", examine: "Check support routes, documentation quality, status communication, ownership information, and whether the provider explains limitations and changes clearly.", test: "Send one ordinary pre-sale or setup question, or search the support documentation for your likely failure. Record whether the answer is specific and usable.", failure: "Equating a large brand or polished site with dependable support, or treating silence about incidents as evidence that none occurred.", evidence: "Official documentation and disclosures establish provider statements; independent reporting and testing can add context but may be incomplete.", pause: "Pause when basic support, recovery, or service-continuity questions have no credible answer." },
  { title: "8. Exit difficulty", why: "A purchase also creates an exit decision. The ability to cancel, recover, export, and migrate determines how much commitment the software really requires.", examine: "Find cancellation, refund, auto-renewal, account deletion, recovery access, export format, migration steps, proprietary-format risks, and the time and effort to switch.", test: "Read the provider’s cancellation and export instructions before subscribing. If possible, export a small sample and confirm it is usable elsewhere; do not assume export equals migration.", failure: "Waiting until renewal or account loss to discover that cancellation requires a particular channel, data export is limited, or recovery depends on one unavailable factor.", evidence: "Current terms, help documentation, export specifications, and a bounded sample export are useful. Provider claims about portability remain claims until checked.", pause: "Pause when you cannot identify how to leave, recover access, or retrieve important data. A low entry price does not offset high lock-in." },
  { title: "9. Real-world testing", why: "Documentation can describe capability but cannot tell you whether the complete workflow fits your device, habits, and failure tolerance.", examine: "Test the normal success path and one failure path using the device, account, network, and data you actually use.", test: "For success, complete the motivating task. For failure, try password recovery, file restoration, export, cancellation, support, reconnecting after a network failure, or restoring access on a new device—whichever is relevant.", failure: "Testing only the impressive demo, assuming a trial covers every workflow, or mistaking a successful setup for reliable long-term use.", evidence: "Your dated task notes and observed limitations are firsthand evidence. This guide includes no CBT product test or product verdict.", pause: "Do not subscribe when the core task or a reasonable failure path cannot be tested and the remaining uncertainty is material." },
  { title: "10. Final evidence-based decision", why: "A decision is stronger when it shows how evidence led to the result and where uncertainty remains.", examine: "Separate verified facts, provider claims, personal tests, independent evidence, and unresolved questions. Compare against your must-haves, not against a universal winner.", test: "Complete the worksheet below, then ask: ‘Would I still choose this if there were no discount, ranking, or affiliate link?’",
    failure: "Using a score that hides a failed must-have, adding unsupported precision, or allowing a good first impression to override unresolved exit or privacy risks.", evidence: "The strongest evidence for the decision should be visible beside the requirement it supports. Keep conflicting evidence and unknowns rather than smoothing them away.", pause: "Buy only when the likely benefit justifies cost and friction. Choosing an existing tool, a free option, or nothing is a valid evidence-based result." },
];

const categories = [
  ["VPNs", "Problem: public-Wi-Fi privacy, travel access, or a specific network need. Test: connect, disconnect, and reconnect on your real network and device. Tradeoff: added complexity or changed routing does not equal anonymity. Exit concern: renewal, cancellation, and what happens to account access after uninstalling."],
  ["Password managers", "Problem: repeated password reuse, poor capture, or access across devices. Test: create, autofill, edit, recover, and restore access on a new device. Tradeoff: convenience depends on a recovery model you accept. Exit concern: export format, emergency access, and whether you can retrieve the vault if the provider is unavailable."],
  ["Cloud storage", "Problem: access and collaboration for files—not automatically independent backup. Test: share, edit, restore an older version, and export a sample. Tradeoff: sync, sharing, recovery, and backup have different failure boundaries. Exit concern: permissions, links, versions, formats, and migration time."],
  ["Data-removal services", "Problem: reducing a defined kind of personal-data exposure. Test: inspect coverage and reporting for your location and identity, then understand reappearance and follow-up. Tradeoff: removal is not disappearance from every source. Exit concern: cancellation, data deletion, and what reports remain available."],
  ["Cybersecurity tools", "Problem: a specific protection gap beyond what your operating system already provides. Test: review alerts, recovery, support, and overlap in a safe way; do not invent malware tests. Tradeoff: more modules can mean cost, prompts, or duplicated controls. Exit concern: renewal, uninstalling cleanly, and what protections remain afterward."],
];

const worksheet = ["Problem to solve", "Required outcomes", "Must-have requirements", "Optional features", "Verified facts", "Provider claims", "What I personally tested", "Unresolved questions", "First-term cost", "Renewal cost", "Cancellation / refund / auto-renewal terms", "Export, recovery, and migration options", "Final decision and reason"];
const faqs = [
  ["Should I always choose the software with the most features?", "No. Features matter only when they support a required outcome. Extra features can add cost, setup work, confusion, or unused capability."],
  ["Is a free plan enough?", "Sometimes. Compare its limits with your actual workflow, how the provider funds it, what data practices apply, and what happens if you outgrow it."],
  ["What should I test before subscribing?", "Test the one task that motivated the purchase and one relevant failure path, such as recovery, export, support, cancellation, restoration, or reconnecting after a network failure."],
  ["When should I not buy software?", "Do not buy when the problem is minor, an existing tool already solves it, the evidence is too weak, switching is too difficult, or the recurring cost exceeds the likely benefit."],
];

export function HowToChooseSoftwarePage() {
  const faqSchema = { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: faqs.map(([question, answer]) => ({ "@type": "Question", name: question, acceptedAnswer: { "@type": "Answer", text: answer } })) };
  const articleSchema = { "@context": "https://schema.org", "@type": "Article", headline: "How to Choose Software: A Practical Buyer's Guide", description: "A practical framework for evaluating software fit, cost, privacy, usability, limits, and switching risk before you subscribe.", author: { "@type": "Organization", name: site.name }, publisher: { "@type": "Organization", name: site.name }, mainEntityOfPage: site.url + "/guides/how-to-choose-software" };
  return <>
    <SEO title="How to Choose Software: A Practical Buyer's Guide" description="Use a practical, evidence-based framework to choose software based on fit, cost, usability, privacy, limits, and switching risk." path="/guides/how-to-choose-software" />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(articleSchema) }} />
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
    <PageHeader eyebrow="Software buying guide" title="How to Choose Software: A Practical Buyer’s Guide" description="Choose software by the problem it solves, the friction it creates, and the evidence behind its claims—not by feature count alone." />
    <Section containerClassName="max-w-4xl">
      <div className="prose prose-slate max-w-none"><h2>Quick answer</h2><p>Start with the problem, define the outcome, and write down the few things the software must do. Then compare true cost, usability, limits, privacy and security context, provider reliability, and how difficult it would be to leave. Test one normal task and one failure path before paying, record what is known and unknown, and be willing not to buy.</p><h2>The Better Software Decision Framework</h2><p>Each step below produces a decision record. The framework is designed for software and online services, not physical technology. Use the same sequence for a VPN, password manager, cloud-storage service, data-removal service, or cybersecurity tool; change the test to match the risk.</p></div>
      <div className="mt-8 space-y-6">{steps.map((step) => <article key={step.title} className="rounded-lg border border-slate-200 bg-white p-6 shadow-soft"><h3 className="text-xl font-bold text-slate-950">{step.title}</h3><dl className="mt-4 grid gap-4 text-sm leading-6 sm:grid-cols-2"><div><dt className="font-semibold text-slate-950">Why it matters</dt><dd className="text-slate-700">{step.why}</dd></div><div><dt className="font-semibold text-slate-950">What to examine</dt><dd className="text-slate-700">{step.examine}</dd></div><div><dt className="font-semibold text-slate-950">Practical question or test</dt><dd className="text-slate-700">{step.test}</dd></div><div><dt className="font-semibold text-slate-950">Common failure mode</dt><dd className="text-slate-700">{step.failure}</dd></div><div><dt className="font-semibold text-slate-950">Useful evidence</dt><dd className="text-slate-700">{step.evidence}</dd></div><div><dt className="font-semibold text-slate-950">When to pause or reject</dt><dd className="text-slate-700">{step.pause}</dd></div></dl></article>)}</div>
      <div className="prose prose-slate mt-12 max-w-none"><h2>Your software evidence worksheet</h2><p>Copy these prompts into a note or spreadsheet. Keeping facts, claims, tests, and unknowns separate prevents a persuasive feature page from becoming your entire decision.</p></div>
      <div className="mt-6 overflow-x-auto rounded-lg border border-slate-200 bg-white shadow-soft"><table className="w-full min-w-[640px] border-collapse text-left text-sm"><thead className="bg-slate-950 text-white"><tr><th className="w-1/3 px-4 py-4" scope="col">Record</th><th className="px-4 py-4" scope="col">Your notes</th></tr></thead><tbody>{worksheet.map((item) => <tr key={item} className="border-b border-slate-200 last:border-0"><th className="bg-slate-50 px-4 py-4 font-semibold text-slate-950" scope="row">{item}</th><td className="h-14 px-4 py-4 text-slate-400">Write what you know, tested, or still need to verify.</td></tr>)}</tbody></table></div>
      <div className="prose prose-slate mt-12 max-w-none"><h2>Apply the framework to common software</h2><p>The categories below are examples, not rankings. They show how the problem, test, tradeoff, and exit concern change while the framework stays reusable.</p></div>
      <div className="mt-6 space-y-4">{categories.map(([category, text]) => <article key={category} className="rounded-lg border border-slate-200 bg-slate-50 p-5"><h3 className="font-bold text-slate-950">{category}</h3><p className="mt-2 text-sm leading-6 text-slate-700">{text}</p></article>)}</div>
      <div className="prose prose-slate mt-12 max-w-none"><h2>When not buying is the right decision</h2><p>A software purchase is not automatically a better outcome. Pause when the problem is not important, an existing tool is good enough, the provider cannot answer basic questions, the normal and failure paths cannot be tested, or the ongoing cost and switching risk outweigh the benefit. Choosing nothing, waiting, or using an existing tool is a valid result.</p><h2>Your final buyer checklist</h2></div>
      <ul className="mt-6 grid gap-3 rounded-lg border border-slate-200 bg-slate-50 p-6 text-sm leading-6 text-slate-700 sm:grid-cols-2">{["I can state the problem in one sentence.","I know the outcome that matters.","I separated requirements from extras.","I calculated first-term and renewal cost.","I found the limits and failure cases.","I checked privacy and security evidence.","I know how to cancel and export.","I tested a normal task and a failure path.","I recorded uncertainty.","I am comfortable not buying."].map((item) => <li key={item} className="flex gap-3"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-brand-600" aria-hidden="true" />{item}</li>)}</ul>
      <p className="mt-5 text-sm leading-6 text-slate-600">Want a reusable version? The Better Software Buyer Checklist is available through the newsletter signup below, alongside future beginner-friendly software guidance.</p>
      <div className="prose prose-slate mt-12 max-w-none"><h2>Frequently asked questions</h2>{faqs.map(([q, a]) => <div key={q}><h3>{q}</h3><p>{a}</p></div>)}<h2>Sources and methodology</h2><p>This guide synthesizes the <Link to="/about/how-we-review-software">Choose Better Tech review methodology</Link> with usability guidance from <a href="https://www.nist.gov/publications/common-industry-specification-usability-requirements" rel="noreferrer">NIST</a>, subscription guidance from the <a href="https://consumer.ftc.gov/articles/getting-and-out-free-trials-auto-renewals-and-negative-option-subscriptions" rel="noreferrer">FTC</a>, and privacy-by-design guidance from the <a href="https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/accountability-and-governance/guide-to-accountability-and-governance/data-protection-by-design-and-by-default/" rel="noreferrer">ICO</a>. No product was ranked or hands-on tested for this cross-category guide. For category-specific decisions, continue to the <Link to="/guides/vpn-buying-guide">VPN Buying Guide</Link>, <Link to="/best-password-managers-for-beginners">password-manager guide</Link>, <Link to="/best-cloud-storage-for-beginners">cloud-storage guide</Link>, <Link to="/best-data-removal-services">data-removal guide</Link>, or <Link to="/best-antivirus-software">cybersecurity tools guide</Link>. See the <Link to="/affiliate-disclosure">Affiliate Disclosure</Link> for our commercial policy.</p></div>
    </Section>
  </>;
}
